# Generated by Django 5.0.4 on 2024-04-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('surname', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=55)),
                ('avatar', models.ImageField(upload_to='static/users/avatar/')),
                ('products', models.ManyToManyField(to='ITSI_ID.products', verbose_name='products')),
                ('team', models.ManyToManyField(to='ITSI_ID.users', verbose_name='team')),
            ],
        ),
    ]
