# Generated by Django 5.0.4 on 2024-04-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSI_ID', '0005_alter_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatar'),
        ),
        migrations.AlterField(
            model_name='users',
            name='products',
            field=models.ManyToManyField(blank=True, to='ITSI_ID.products', verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='users',
            name='team',
            field=models.ManyToManyField(blank=True, to='ITSI_ID.users', verbose_name='team'),
        ),
    ]
