# Generated by Django 5.0.4 on 2024-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSI_ID', '0007_alter_users_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='services',
            field=models.ManyToManyField(blank=True, to='ITSI_ID.services', verbose_name='services'),
        ),
    ]
