# Generated by Django 5.0.4 on 2024-04-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSI_ID', '0008_services_users_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('user_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='analytics',
            field=models.ManyToManyField(blank=True, to='ITSI_ID.api', verbose_name='analytics'),
        ),
    ]
