# Generated by Django 5.0.4 on 2024-04-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSI_ID', '0009_api_users_analytics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='user_count',
            new_name='April',
        ),
        migrations.RemoveField(
            model_name='api',
            name='month',
        ),
        migrations.AddField(
            model_name='api',
            name='August',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api',
            name='December',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api',
            name='February',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api',
            name='January',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api',
            name='July',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api',
            name='June',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api',
            name='March',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api',
            name='May',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api',
            name='November',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api',
            name='October',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api',
            name='September',
            field=models.IntegerField(default=0),
        ),
    ]
